// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZbW.CarRentify.CarManagement.Infrastructure;

namespace ZbW.CarRentify.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZbW.CarRentify.CarManagement.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ZbW.CarRentify.CarManagement.Domain.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ModelId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ZbW.CarRentify.CarManagement.Domain.CarClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("CarClass");
                });

            modelBuilder.Entity("ZbW.CarRentify.CarManagement.Domain.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BrandId");

                    b.Property<Guid?>("BrandId1");

                    b.Property<Guid?>("CarClassId");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("BrandId1");

                    b.HasIndex("CarClassId");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("ZbW.CarRentify.CarManagement.Domain.Car", b =>
                {
                    b.HasOne("ZbW.CarRentify.CarManagement.Domain.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");
                });

            modelBuilder.Entity("ZbW.CarRentify.CarManagement.Domain.Model", b =>
                {
                    b.HasOne("ZbW.CarRentify.CarManagement.Domain.Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId");

                    b.HasOne("ZbW.CarRentify.CarManagement.Domain.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId1");

                    b.HasOne("ZbW.CarRentify.CarManagement.Domain.CarClass", "CarClass")
                        .WithMany()
                        .HasForeignKey("CarClassId");
                });
#pragma warning restore 612, 618
        }
    }
}
